name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
        
    - name: Installing protoc-gen-go
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
        export PATH="$PATH:$(go env GOPATH)/bin"

    - name: Build
      run: |
        mkdir -p internal/genproto
        protoc --proto_path=api/protobuf \
        --go_out=internal/genproto --go_opt=paths=source_relative \
        --go-grpc_out=internal/genproto --go-grpc_opt=paths=source_relative \
        rcs.proto
        go build -v -o ./bin/rcs ./cmd

    - name: Test
      run: go test -v ./internal/**
